#!/usr/bin/perl -w

# Generate usys.S, the stubs for syscalls.

print "# generated by usys.pl - do not edit\n";

print "#include \"kernel/syscall.h\"\n";

sub entry {
    my $name = shift;
    my $sysno = shift || $name;
    my $sym = "__sys_$name";
    print ".global $sym\n";
    print "$sym:\n";
    print " li a7, SYS_${sysno}\n";
    print " ecall\n";
    print " ret\n";
}
	
entry("clone");
entry("exit");
entry("exit_group");
entry("wait4");
entry("pipe2");
entry("read");
entry("write");
entry("close");
entry("kill");
entry("execve");
entry("openat");
entry("mknodat");
entry("unlinkat");
entry("fstat");
entry("linkat");
entry("mkdirat");
entry("chdir");
entry("dup");
entry("getpid");
entry("getdents64");
entry("brk");
entry("sbrk");
entry("pause");
entry("uptime");
entry("interpose");
entry("pgpte");
entry("kpgtbl");
entry("sigalarm");
entry("sigreturn");
entry("bind");
entry("unbind");
entry("send");
entry("recv");
entry("cpupin");
entry("mmap");
entry("munmap");
